#!/bin/bash

# Complex Query Examples for Enhanced zaq
# Usage: ./complex_queries.sh <query> [data_file]

DATA_FILE="${2:-/home/ubuntu/jaq/test_data.json}"

# Display help if no query provided
if [ -z "$1" ]; then
    echo "zaq Enhanced - Complex Query Examples"
    echo "======================================"
    echo ""
    echo "Usage: $0 <query> [data_file]"
    echo "  query   - zaq query string"
    echo "  data_file - Path to JSON data file (default: $DATA_FILE)"
    echo ""
    echo "Example Queries:"
    echo ""
    echo "Array Operations:"
    echo "  ./complex_queries.sh '.arrays.simple | length'"
    echo "  ./complex_queries.sh '.arrays.numbers | add'"
    echo "  ./complex_queries.sh '.arrays.numbers | mean'"
    echo "  ./complex_queries.sh '.arrays.numbers | min'"
    echo "  ./complex_queries.sh '.arrays.numbers | max'"
    echo "  ./complex_queries.sh '.arrays.numbers | reverse'"
    echo "  ./complex_queries.sh '.arrays.numbers | sort'"
    echo ""
    echo "Object Operations:"
    echo "  ./complex_queries.sh '.objects.simple | keys'"
    echo "  ./complex_queries.sh '.objects.simple | values'"
    echo "  ./complex_queries.sh '.objects.simple | entries'"
    echo "  ./complex_queries.sh '.objects.simple | to_entries'"
    echo ""
    echo "String Operations:"
    echo "  ./complex_queries.sh '.strings.simple | length'"
    echo "  ./complex_queries.sh '.strings.simple | contains'zaq'"
    echo "  ./complex_queries.sh '.strings.sentences[0] | startswith'The'"
    echo "  ./complex_queries.sh '.strings.sentences[0] | endswith'dog'"
    echo "  ./complex_queries.sh '.strings.substrings | split'app'|'"
    echo ""
    echo "Math Operations:"
    echo "  ./complex_queries.sh '.math.numbers | map(floor) | .[]'"
    echo "  ./complex_queries.sh '.math.numbers | map(ceil) | .[]'"
    echo "  ./complex_queries.sh '.math.numbers | map(round) | .[]'"
    echo "  ./complex_queries.sh '.math.for_sqrt | map(sqrt) | .[]'"
    echo "  ./complex_queries.sh '.math.for_pow | map(pow(.;2)) | .[]'"
    echo "  ./complex_queries.sh '.math.for_log | map(log) | .[]'"
    echo ""
    echo "Type Operations:"
    echo "  ./complex_queries.sh '.types.mixed | map(type) | .[]'"
    echo ""
    echo "Complex Queries:"
    echo "  ./complex_queries.sh '.objects.simple | to_entries | map({key: .key, value: .value})'"
    echo "  ./complex_queries.sh '.arrays.duplicates | unique'"
    echo "  ./complex_queries.sh '.aggregation.data | sort'"
    echo "  ./complex_queries.sh '.aggregation.data | reverse | .[0:3]'"
    echo "  ./complex_queries.sh '.aggregation.data | add'"
    echo "  ./complex_queries.sh '.aggregation.data | min'"
    echo "  ./complex_queries.sh '.aggregation.data | max'"
    echo "  ./complex_queries.sh '.aggregation.data | mean'"
    echo ""
    echo "Nested Object Access:"
    echo "  ./complex_queries.sh '.nested | .user.profile.name'"
    echo "  ./complex_queries.sh '.nested | .user.profile.preferences.color'"
    echo ""
    echo "Path Operations:"
    echo "  ./complex_queries.sh '.paths.flat | paths'"
    echo "  ./complex_queries.sh '.paths.nested | recurse | .[]'"
    echo ""
    echo "Note: This script requires the enhanced zaq binary."
    echo "      Run: ./zig-out/bin/zaq <query> $DATA_FILE"
    exit 0
fi

QUERY="$1"
echo "Running zaq with query: $QUERY"
echo "Data file: $DATA_FILE"
echo ""

# Run zaq with the specified query
./zig-out/bin/zaq "$QUERY" "$DATA_FILE"
